apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: nginx-test 
spec:
  # ports:
  ports:
    - name: http
      port: 9097
      protocol: TCP
      targetPort: 9097
  selector:
    app: nginx-test
  type: NodePort