apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: nginx:1.21.4
        name: nginx-test
        ports:
        - containerPort: 80